server:
    error:
        include-exception: true
        include-message: always
        include-stacktrace: never
    port: 9088
spring:
    application:
        name: email-service
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialization-mode: always
        password: ${DBPASSWORD}
        url: jdbc:mysql://${EMAIL_HOSTNAME}:3306/${EMAIL_BASE}?useSSL=false
        username: ${DBUSERNAME}
    freemarker:
        checkTemplateLocation: false
        template-loader-path: classpath:/templates
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        password:${EMAILPASSWORD}
        port: 25
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp
        username:${EMAILUSER}
